package Conductores;


/**
* Conductores/Conductor.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from conductor.idl
* lunes 13 de mayo de 2019 05:14:30 PM COT
*/

public interface Conductor extends ConductorOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Conductor
