package Conductores;


/**
* Conductores/ConductorHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from conductor.idl
* lunes 13 de mayo de 2019 05:14:30 PM COT
*/

abstract public class ConductorHelper
{
  private static String  _id = "IDL:Conductores/Conductor:1.0";

  public static void insert (org.omg.CORBA.Any a, Conductores.Conductor that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Conductores.Conductor extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (Conductores.ConductorHelper.id (), "Conductor");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Conductores.Conductor read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_ConductorStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Conductores.Conductor value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static Conductores.Conductor narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Conductores.Conductor)
      return (Conductores.Conductor)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Conductores._ConductorStub stub = new Conductores._ConductorStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static Conductores.Conductor unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Conductores.Conductor)
      return (Conductores.Conductor)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Conductores._ConductorStub stub = new Conductores._ConductorStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
