package Conductores;


/**
* Conductores/ConductorPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from conductor.idl
* lunes 13 de mayo de 2019 05:14:30 PM COT
*/

public abstract class ConductorPOA extends org.omg.PortableServer.Servant
 implements Conductores.ConductorOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("insertarConductor", new java.lang.Integer (0));
    _methods.put ("actualizarConductor", new java.lang.Integer (1));
    _methods.put ("eliminarConductor", new java.lang.Integer (2));
    _methods.put ("consultarConductor", new java.lang.Integer (3));
    _methods.put ("shutdown", new java.lang.Integer (4));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Conductores/Conductor/insertarConductor
       {
         int id = in.read_long ();
         String nombre = in.read_wstring ();
         int telefono = in.read_long ();
         String placa = in.read_wstring ();
         boolean $result = false;
         $result = this.insertarConductor (id, nombre, telefono, placa);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // Conductores/Conductor/actualizarConductor
       {
         int id = in.read_long ();
         String nombre = in.read_wstring ();
         int telefono = in.read_long ();
         String placa = in.read_wstring ();
         boolean $result = false;
         $result = this.actualizarConductor (id, nombre, telefono, placa);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 2:  // Conductores/Conductor/eliminarConductor
       {
         int id = in.read_long ();
         boolean $result = false;
         $result = this.eliminarConductor (id);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 3:  // Conductores/Conductor/consultarConductor
       {
         int id = in.read_long ();
         String $result = null;
         $result = this.consultarConductor (id);
         out = $rh.createReply();
         out.write_wstring ($result);
         break;
       }

       case 4:  // Conductores/Conductor/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Conductores/Conductor:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Conductor _this() 
  {
    return ConductorHelper.narrow(
    super._this_object());
  }

  public Conductor _this(org.omg.CORBA.ORB orb) 
  {
    return ConductorHelper.narrow(
    super._this_object(orb));
  }


} // class ConductorPOA
