package RegistroApp;


/**
* RegistroApp/RegistroOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Registro.idl
* miércoles 8 de mayo de 2019 09:33:33 PM COT
*/

public interface RegistroOperations 
{
  boolean insertarRegistro (String nombres, String apellidos, int tipo, String direccion, int identificacion, String telefono, String email, String rol, String contrasena);
  boolean actualizarRegistro (String nombres, String apellidos, int tipo, String direccion, int identificacion, String telefono, String email, String rol, String contrasena);
  boolean eliminarRegistro (int identificacion);
  String consultarRegistro (int identificacion);
  void shutdown ();
} // interface RegistroOperations
