package RegistroApp;


/**
* RegistroApp/Registro.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Registro.idl
* miércoles 8 de mayo de 2019 09:33:33 PM COT
*/

public interface Registro extends RegistroOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Registro
