package RegistroApp;

/**
* RegistroApp/RegistroHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Registro.idl
* miércoles 8 de mayo de 2019 09:33:33 PM COT
*/

public final class RegistroHolder implements org.omg.CORBA.portable.Streamable
{
  public RegistroApp.Registro value = null;

  public RegistroHolder ()
  {
  }

  public RegistroHolder (RegistroApp.Registro initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = RegistroApp.RegistroHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    RegistroApp.RegistroHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return RegistroApp.RegistroHelper.type ();
  }

}
