package Proveedores;


/**
* Proveedores/Proveedor.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from proveedor.idl
* lunes 13 de mayo de 2019 05:15:19 PM COT
*/

public interface Proveedor extends ProveedorOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Proveedor
