package Proveedores;


/**
* Proveedores/ProveedorHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from proveedor.idl
* lunes 13 de mayo de 2019 05:15:19 PM COT
*/

abstract public class ProveedorHelper
{
  private static String  _id = "IDL:Proveedores/Proveedor:1.0";

  public static void insert (org.omg.CORBA.Any a, Proveedores.Proveedor that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Proveedores.Proveedor extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (Proveedores.ProveedorHelper.id (), "Proveedor");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Proveedores.Proveedor read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_ProveedorStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Proveedores.Proveedor value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static Proveedores.Proveedor narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Proveedores.Proveedor)
      return (Proveedores.Proveedor)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Proveedores._ProveedorStub stub = new Proveedores._ProveedorStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static Proveedores.Proveedor unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Proveedores.Proveedor)
      return (Proveedores.Proveedor)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Proveedores._ProveedorStub stub = new Proveedores._ProveedorStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
