module Clientes {
    interface Cliente{
        boolean insertarCliente(in long codigoCliente,in long Nit, in wstring nombre, in wstring apellidos, in wstring telefono, in wstring correo );
        
        boolean actualizarCliente(in long codigoCliente,in long Nit, in wstring nombre, in wstring apellidos, in wstring telefono, in wstring correo );

        boolean eliminarCliente(in long Cod_cliente);
        
        wstring consultarCliente(in long Cod_cliente);
       
        oneway void shutdown();
        
    };

};


