module Ventas {

    interface Venta{

        boolean insertarVenta(in long id_venta,in double subtotal, in double iva, in double total_pagar);
        
        boolean actualizarVenta(in long id_venta,in double subtotal, in double iva, in double total_pagar);

        boolean eliminarVenta(in long id_venta);

        wstring consultarVenta(in long id_venta);

       
        oneway void shutdown();
        
    };

};
