package Producto;


/**
* Producto/ProductosHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from producto.idl
* lunes 13 de mayo de 2019 05:15:01 PM COT
*/

abstract public class ProductosHelper
{
  private static String  _id = "IDL:Producto/Productos:1.0";

  public static void insert (org.omg.CORBA.Any a, Producto.Productos that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Producto.Productos extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (Producto.ProductosHelper.id (), "Productos");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Producto.Productos read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_ProductosStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Producto.Productos value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static Producto.Productos narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Producto.Productos)
      return (Producto.Productos)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Producto._ProductosStub stub = new Producto._ProductosStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static Producto.Productos unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Producto.Productos)
      return (Producto.Productos)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Producto._ProductosStub stub = new Producto._ProductosStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
