package Producto;


/**
* Producto/ProductosOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from producto.idl
* lunes 13 de mayo de 2019 05:15:01 PM COT
*/

public interface ProductosOperations 
{
  boolean insertarProveedor (int id, String nombre, int precio, int id_proveedor);
  boolean actualizarProveedor (int id, String nombre, int precio, int id_proveedor);
  boolean eliminarProveedor (int id);
  String consultarProveedor (int id);
  void shutdown ();
} // interface ProductosOperations
