package Producto;


/**
* Producto/ProductosPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from producto.idl
* lunes 13 de mayo de 2019 05:15:01 PM COT
*/

public abstract class ProductosPOA extends org.omg.PortableServer.Servant
 implements Producto.ProductosOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("insertarProveedor", new java.lang.Integer (0));
    _methods.put ("actualizarProveedor", new java.lang.Integer (1));
    _methods.put ("eliminarProveedor", new java.lang.Integer (2));
    _methods.put ("consultarProveedor", new java.lang.Integer (3));
    _methods.put ("shutdown", new java.lang.Integer (4));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Producto/Productos/insertarProveedor
       {
         int id = in.read_long ();
         String nombre = in.read_wstring ();
         int precio = in.read_long ();
         int id_proveedor = in.read_long ();
         boolean $result = false;
         $result = this.insertarProveedor (id, nombre, precio, id_proveedor);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // Producto/Productos/actualizarProveedor
       {
         int id = in.read_long ();
         String nombre = in.read_wstring ();
         int precio = in.read_long ();
         int id_proveedor = in.read_long ();
         boolean $result = false;
         $result = this.actualizarProveedor (id, nombre, precio, id_proveedor);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 2:  // Producto/Productos/eliminarProveedor
       {
         int id = in.read_long ();
         boolean $result = false;
         $result = this.eliminarProveedor (id);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 3:  // Producto/Productos/consultarProveedor
       {
         int id = in.read_long ();
         String $result = null;
         $result = this.consultarProveedor (id);
         out = $rh.createReply();
         out.write_wstring ($result);
         break;
       }

       case 4:  // Producto/Productos/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Producto/Productos:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Productos _this() 
  {
    return ProductosHelper.narrow(
    super._this_object());
  }

  public Productos _this(org.omg.CORBA.ORB orb) 
  {
    return ProductosHelper.narrow(
    super._this_object(orb));
  }


} // class ProductosPOA
