package Clientes;


/**
* Clientes/ClienteOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from cliente.idl
* miércoles 22 de mayo de 2019 03:16:34 PM COT
*/

public interface ClienteOperations 
{
  boolean insertarCliente (int codigoCliente, int Nit, String nombre, String apellidos, String telefono, String correo);
  boolean actualizarCliente (int codigoCliente, int Nit, String nombre, String apellidos, String telefono, String correo);
  boolean eliminarCliente (int Cod_cliente);
  String consultarCliente (int Cod_cliente);
  void shutdown ();
} // interface ClienteOperations
