package Clientes;


/**
* Clientes/Cliente.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from cliente.idl
* miércoles 22 de mayo de 2019 03:16:34 PM COT
*/

public interface Cliente extends ClienteOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Cliente
