package Clientes;


/**
* Clientes/Cliente.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from cliente.idl
* lunes 13 de mayo de 2019 04:14:41 PM COT
*/

public interface Cliente extends ClienteOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Cliente
