package Clientes;


/**
* Clientes/ClienteOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from cliente.idl
* lunes 13 de mayo de 2019 04:14:41 PM COT
*/

public interface ClienteOperations 
{
  boolean insertarCliente (int codigoCliente, String Nit, String nombre, int telefono, String direccion);
  boolean actualizarCliente (int codigoCliente, String Nit, String nombre, int telefono, String direccion);
  boolean eliminarCliente (int Cod_cliente);
  String consultarCliente (int Cod_cliente);
  void shutdown ();
} // interface ClienteOperations
