package Clientes;

/**
* Clientes/ClienteHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from cliente.idl
* miércoles 22 de mayo de 2019 03:16:34 PM COT
*/

public final class ClienteHolder implements org.omg.CORBA.portable.Streamable
{
  public Clientes.Cliente value = null;

  public ClienteHolder ()
  {
  }

  public ClienteHolder (Clientes.Cliente initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Clientes.ClienteHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Clientes.ClienteHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Clientes.ClienteHelper.type ();
  }

}
