/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;
import java.sql.ResultSet;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Principales.*;

/**
 *
 * @author USER
 */
public class RegistoProductos extends   javax.swing.JFrame {
    private DefaultTableModel modelotable;
     private  DefaultComboBoxModel modelocombo;
    /**
     * Creates new form Productos
     */
    public RegistoProductos() {
        initComponents();
         modelotable = new DefaultTableModel(null, getColumn());
         modelocombo = new DefaultComboBoxModel(new String [] {});
        initComponents();
        //Instancion al clase productos
        Principales.Producto objTablaProducto = new Principales.Producto();
        
        //ResultSet
        ResultSet estados;
        //Instancio la clase estados
        estados = objTablaProducto.consultarEstado();
        try {
            //Recorremos el resultado generado por la consulta
            while(estados.next()){
                //Con el metodo addElement vamos a agregar cada resultado al comboBox
                modelocombo.addElement(new Estado(estados.getInt("Cod_proveedor"), estados.getString("nombre")));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Consulta no hecha"+e.getMessage());
        }
  
    }
    
          
         private String[] getColumn(){
        String columnas[] = new String[]{"id","nombre","precio","id_proveedor"};
        return columnas;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtidproducto = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lblidproducto = new javax.swing.JLabel();
        txtnombreproducto = new javax.swing.JTextField();
        lblNombreproducto = new javax.swing.JLabel();
        lblpreciop = new javax.swing.JLabel();
        lblprovedor = new javax.swing.JLabel();
        txtpreciop = new javax.swing.JTextField();
        cboEstado = new javax.swing.JComboBox<>();
        btnAdicionar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblproducto = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        txtidproducto.setBackground(new java.awt.Color(255, 255, 255));
        txtidproducto.setForeground(new java.awt.Color(0, 0, 0));
        txtidproducto.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 153, 0)));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("REGISTRO PRODUCTOS ");

        lblidproducto.setForeground(new java.awt.Color(0, 0, 0));
        lblidproducto.setText("ID Producto");

        txtnombreproducto.setBackground(new java.awt.Color(255, 255, 255));
        txtnombreproducto.setForeground(new java.awt.Color(0, 0, 0));
        txtnombreproducto.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 153, 0)));

        lblNombreproducto.setForeground(new java.awt.Color(0, 0, 0));
        lblNombreproducto.setText("Nombre del producto ");

        lblpreciop.setForeground(new java.awt.Color(0, 0, 0));
        lblpreciop.setText("Precio del Prodcuto");

        lblprovedor.setForeground(new java.awt.Color(0, 0, 0));
        lblprovedor.setText("Proveedor");

        txtpreciop.setBackground(new java.awt.Color(255, 255, 255));
        txtpreciop.setForeground(new java.awt.Color(0, 0, 0));
        txtpreciop.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 153, 0)));

        cboEstado.setModel(modelocombo);
        cboEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboEstadoActionPerformed(evt);
            }
        });

        btnAdicionar.setText("Guardar");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombreproducto)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblidproducto)
                                    .addComponent(lblpreciop)
                                    .addComponent(lblprovedor)
                                    .addComponent(btnAdicionar))
                                .addGap(48, 48, 48)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cboEstado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtnombreproducto, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                                    .addComponent(txtidproducto, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                                    .addComponent(txtpreciop))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtidproducto, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblidproducto))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnombreproducto, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombreproducto))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtpreciop, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblpreciop))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblprovedor))
                .addGap(82, 82, 82)
                .addComponent(btnAdicionar)
                .addContainerGap(200, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 600));

        jPanel2.setBackground(new java.awt.Color(255, 153, 51));

        tblproducto.setForeground(new java.awt.Color(255, 255, 255));
        tblproducto.setModel(modelotable);
        jScrollPane1.setViewportView(tblproducto);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/back_100px.png"))); // NOI18N
        jLabel2.setText("Atras");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 580, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboEstadoActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
            Menu objRegistro = new Menu();
            objRegistro.setVisible(true);
            this.setVisible(false);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed

        //Validar los campos vac{ios
            if(txtidproducto.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Ingrese id del proctud");
                txtidproducto.requestFocus();
                return;
            }

            if(txtnombreproducto.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Ingrese Nombre del Producto");
                txtnombreproducto.requestFocus();
                return;
            }

            if(txtpreciop.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Ingrese Precio del producto");
                txtpreciop.requestFocus();
                return;
            }

            //Creamos un objeto
            Estado objEstado = (Estado) cboEstado.getSelectedItem();
            //Asignamos el atributo del objeto seleccionado en el combo.
            int estado = objEstado.getCod_proveedor(); //Ya aquí tenemos el id del estado seleccionado.

            if (objEstado == null) {
                JOptionPane.showMessageDialog(null, "Ingrese Proveedor");
                return;
            }

            //Instancio la clase
            Principales.Producto objTablaProducto = new Principales.Producto();

            //Declaro variables
            int id;
            String nombre;
            int id_estado = estado;
            int precio;

            //Asigno los valores del formualrio
            id = Integer.parseInt(txtidproducto.getText());
            nombre = txtnombreproducto.getText();
            precio = Integer.parseInt(txtpreciop.getText());
            System.out.println(id_estado);
            //Envio los datos
            boolean resultado = objTablaProducto.insertarProveedor(id,nombre,precio,id_estado);
            if(resultado == true){
                JOptionPane.showMessageDialog(null, "Registro exitoso");
            }else{
                JOptionPane.showMessageDialog(null, "Registro no exitoso");

            }

            //Limpio los campos
            txtidproducto.setText("");
            txtnombreproducto.setText("");
            txtpreciop.setText("");
            //txtTelefono.setText("");
    }//GEN-LAST:event_btnAdicionarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistoProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistoProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistoProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistoProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistoProductos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JComboBox<String> cboEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNombreproducto;
    private javax.swing.JLabel lblidproducto;
    private javax.swing.JLabel lblpreciop;
    private javax.swing.JLabel lblprovedor;
    private javax.swing.JTable tblproducto;
    private javax.swing.JTextField txtidproducto;
    private javax.swing.JTextField txtnombreproducto;
    private javax.swing.JTextField txtpreciop;
    // End of variables declaration//GEN-END:variables
}
