package Sucursales;


/**
* Sucursales/Sucursal.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from sucursal.idl
* lunes 13 de mayo de 2019 05:15:35 PM COT
*/

public interface Sucursal extends SucursalOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Sucursal
