package Sucursales;


/**
* Sucursales/SucursalPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from sucursal.idl
* lunes 13 de mayo de 2019 05:15:35 PM COT
*/

public abstract class SucursalPOA extends org.omg.PortableServer.Servant
 implements Sucursales.SucursalOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("insertarSucursal", new java.lang.Integer (0));
    _methods.put ("actualizarSucursal", new java.lang.Integer (1));
    _methods.put ("eliminarSucursal", new java.lang.Integer (2));
    _methods.put ("consultarSucursal", new java.lang.Integer (3));
    _methods.put ("shutdown", new java.lang.Integer (4));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Sucursales/Sucursal/insertarSucursal
       {
         int codigo = in.read_long ();
         String ciudad = in.read_wstring ();
         int telefono = in.read_long ();
         String direccion = in.read_wstring ();
         boolean $result = false;
         $result = this.insertarSucursal (codigo, ciudad, telefono, direccion);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // Sucursales/Sucursal/actualizarSucursal
       {
         int codigo = in.read_long ();
         String ciudad = in.read_wstring ();
         int telefono = in.read_long ();
         String direccion = in.read_wstring ();
         boolean $result = false;
         $result = this.actualizarSucursal (codigo, ciudad, telefono, direccion);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 2:  // Sucursales/Sucursal/eliminarSucursal
       {
         int Codigo = in.read_long ();
         boolean $result = false;
         $result = this.eliminarSucursal (Codigo);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 3:  // Sucursales/Sucursal/consultarSucursal
       {
         int Codigo = in.read_long ();
         String $result = null;
         $result = this.consultarSucursal (Codigo);
         out = $rh.createReply();
         out.write_wstring ($result);
         break;
       }

       case 4:  // Sucursales/Sucursal/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Sucursales/Sucursal:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Sucursal _this() 
  {
    return SucursalHelper.narrow(
    super._this_object());
  }

  public Sucursal _this(org.omg.CORBA.ORB orb) 
  {
    return SucursalHelper.narrow(
    super._this_object(orb));
  }


} // class SucursalPOA
