package Sucursales;


/**
* Sucursales/SucursalHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from sucursal.idl
* lunes 13 de mayo de 2019 05:15:35 PM COT
*/

abstract public class SucursalHelper
{
  private static String  _id = "IDL:Sucursales/Sucursal:1.0";

  public static void insert (org.omg.CORBA.Any a, Sucursales.Sucursal that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Sucursales.Sucursal extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (Sucursales.SucursalHelper.id (), "Sucursal");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Sucursales.Sucursal read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_SucursalStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Sucursales.Sucursal value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static Sucursales.Sucursal narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Sucursales.Sucursal)
      return (Sucursales.Sucursal)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Sucursales._SucursalStub stub = new Sucursales._SucursalStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static Sucursales.Sucursal unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Sucursales.Sucursal)
      return (Sucursales.Sucursal)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Sucursales._SucursalStub stub = new Sucursales._SucursalStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
