package Ventas;


/**
* Ventas/Venta.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from venta.idl
* lunes 13 de mayo de 2019 05:15:46 PM COT
*/

public interface Venta extends VentaOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Venta
