package Ventas;

/**
* Ventas/VentaHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from venta.idl
* lunes 13 de mayo de 2019 05:15:46 PM COT
*/

public final class VentaHolder implements org.omg.CORBA.portable.Streamable
{
  public Ventas.Venta value = null;

  public VentaHolder ()
  {
  }

  public VentaHolder (Ventas.Venta initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Ventas.VentaHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Ventas.VentaHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Ventas.VentaHelper.type ();
  }

}
