package Ventas;


/**
* Ventas/VentaOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from venta.idl
* lunes 13 de mayo de 2019 05:15:46 PM COT
*/

public interface VentaOperations 
{
  boolean insertarVenta (int id_venta, double subtotal, double iva, double total_pagar);
  boolean actualizarVenta (int id_venta, double subtotal, double iva, double total_pagar);
  boolean eliminarVenta (int id_venta);
  String consultarVenta (int id_venta);
  void shutdown ();
} // interface VentaOperations
